version: '3.8'

services:
  payment-db:
    image: postgres:latest
    container_name: payment-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment-db
    ports:
      - "5433:5432"